### ISSUE TITLE
Data Pulling

### ISSUE THREAD

**Issue by kgleach** [ElectroweakGroup/Database_Extraction_Tool#9]
@wmcdonal I pulled all 6+ states in all Pb isotopes.  It plotted, but returned this error:

Traceback (most recent call last):
  File "THIS_WORKS.py", line 63, in <module>
    function(option)
  File "THIS_WORKS.py", line 17, in function
    userInput = ided.datExp(option,True,True)
  File "/home/kleach/Work/Database_Extraction_Tool/newIsotopeDataExportingDat.py", line 19, in datExp
    from GUI import guioutputs
  File "/home/kleach/Work/Database_Extraction_Tool/GUI.py", line 206, in <module>
    class guioutputs:
  File "/home/kleach/Work/Database_Extraction_Tool/GUI.py", line 208, in guioutputs
    Z=app.chemSymVar.upper()
AttributeError: 'StringVar' object has no attribute 'upper'

**Comment by matmarti** [comment]
@kgleach I was playing around this earlier this morning. I just pushed up the fix for this issue
